steps:
  - name: "gcr.io/cloud-builders/docker"
    args: [ "build", "-t", "gcr.io/$PROJECT_ID/backendnote", "." ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "backendnote",
        "--image",
        "gcr.io/$PROJECT_ID/backendnote",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated"
      ]

timeout: "1600s"

options:
  logging: CLOUD_LOGGING_ONLY
