# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker image
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend-service', '.']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy to Cloud Run
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'backend-service',
        '--image', 'gcr.io/$PROJECT_ID/backend-service',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]
options:
  logging: CLOUD_LOGGING_ONLY
